language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
addons:
  postgresql: "9.6"
before_script:
  - export TZ=America/Los_Angeles
  - date
  - psql -U postgres -c "create user test with password 'test';"
  - psql -c 'create database test owner test;' -U postgres
# Skip the default mvn command because we want to set the profile explicitly
install: true
script:
  - mvn -e "-Dhsqldb.database.url=jdbc:hsqldb:file:target/hsqldb;shutdown=true" -Dhsqldb.database.user=SA -Dhsqldb.database.password= -P hsqldb verify
  - mvn -e -Dpostgres.database.url=jdbc:postgresql:test -Dpostgres.database.user=test -Dpostgres.database.password=test -P postgresql verify
  # Deploy Maven artifacts, but only from regular master builds
  - |
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]
    then
      cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -Ppackagecloud -e -DskipTests deploy
    fi
after_failure:
  - echo "\n=== SUREFIRE REPORTS ===\n"
  - for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done
